### ISSUE TITLE
Implement the last 5 day scrape

### ISSUE THREAD

**Issue by lwm** [giving-a-fuck-about-climate-change/carbondoomsday-django#1]
So, I'll add a django command, say, `python manage.py scrape_last_five_days` which calls a celery task (async magic which we can rely on later for pulling in data) and slaps it all in a model (yet to be sorted out in my head but asking over at [the lobby](https://gitter.im/giving-a-fuck-about-climate-change/Lobby).

Will close off https://github.com/giving-a-fuck-about-climate-change/carbon-doomsday/issues/6.

**Comment by titojankowski** [comment]
Nice work!!
